<?php return [
    "Akbolto Prime Barrel",
    "Akbolto Prime Blueprint",
    "Akbolto Prime Link",
    "Akbolto Prime Receiver",
    "Akbolto Prime Set",
    "Akbronco Prime Blueprint",
    "Akbronco Prime Link",
    "Akbronco Prime Set",
    "Aklex Prime Blueprint",
    "Aklex Prime Link",
    "Aklex Prime Set",
    "Akstiletto Prime Barrel",
    "Akstiletto Prime Blueprint",
    "Akstiletto Prime Link",
    "Akstiletto Prime Receiver",
    "Akstiletto Prime Set",
    "Ankyros Prime Blade",
    "Ankyros Prime Blueprint",
    "Ankyros Prime Gauntlet",
    "Ankyros Prime Set",
    "Arcane Acceleration",
    "Arcane Agility",
    "Arcane Avenger",
    "Arcane Awakening",
    "Arcane Barrier",
    "Arcane Eruption",
    "Arcane Guardian",
    "Ash Prime Blueprint",
    "Ash Prime Chassis",
    "Ash Prime Neuroptics",
    "Ash Prime Systems",
    "Ash Prime Set",
    "Ballistica Prime Blueprint",
    "Ballistica Prime Lower Limb",
    "Ballistica Prime Receiver",
    "Ballistica Prime String",
    "Ballistica Prime Upper Limb",
    "Ballistica Prime Set",
    "Banshee Prime Blueprint",
    "Banshee Prime Chassis",
    "Banshee Prime Neuroptics",
    "Banshee Prime Systems",
    "Banshee Prime Set",
    "Bo Prime Blueprint",
    "Bo Prime Handle",
    "Bo Prime Ornament",
    "Bo Prime Set",
    "Boar Prime Barrel",
    "Boar Prime Blueprint",
    "Boar Prime Receiver",
    "Boar Prime Stock",
    "Boar Prime Set",
    "Boltor Prime Barrel",
    "Boltor Prime Blueprint",
    "Boltor Prime Receiver",
    "Boltor Prime Stock",
    "Boltor Prime Set",
    "Braton Prime Barrel",
    "Braton Prime Blueprint",
    "Braton Prime Receiver",
    "Braton Prime Stock",
    "Braton Prime Set",
    "Bronco Prime Barrel",
    "Bronco Prime Blueprint",
    "Bronco Prime Receiver",
    "Bronco Prime Set",
    "Burston Prime Barrel",
    "Burston Prime Blueprint",
    "Burston Prime Receiver",
    "Burston Prime Stock",
    "Burston Prime Set",
    "Carrier Prime Blueprint",
    "Carrier Prime Carapace",
    "Carrier Prime Cerebrum",
    "Carrier Prime Systems",
    "Carrier Prime Set",
    "Cernos Prime Blueprint",
    "Cernos Prime Grip",
    "Cernos Prime Lower Limb",
    "Cernos Prime String",
    "Cernos Prime Upper Limb",
    "Cernos Prime Set",
    "Dakra Prime Blade",
    "Dakra Prime Blueprint",
    "Dakra Prime Handle",
    "Dakra Prime Set",
    "Dual Kamas Prime Blade",
    "Dual Kamas Prime Blueprint",
    "Dual Kamas Prime Handle",
    "Dual Kamas Prime Set",
    "Ember Prime Blueprint",
    "Ember Prime Chassis",
    "Ember Prime Neuroptics",
    "Ember Prime Systems",
    "Ember Prime Set",
    "Euphona Prime Barrel",
    "Euphona Prime Blueprint",
    "Euphona Prime Receiver",
    "Euphona Prime Set",
    "Fang Prime Blade",
    "Fang Prime Blueprint",
    "Fang Prime Handle",
    "Fang Prime Set",
    "Fragor Prime Blueprint",
    "Fragor Prime Handle",
    "Fragor Prime Head",
    "Fragor Prime Set",
    "Frost Prime Blueprint",
    "Frost Prime Chassis",
    "Frost Prime Neuroptics",
    "Frost Prime Systems",
    "Frost Prime Set",
    "Galatine Prime Blade",
    "Galatine Prime Blueprint",
    "Galatine Prime Handle",
    "Galatine Prime Set",
    "Glaive Prime Blade",
    "Glaive Prime Blueprint",
    "Glaive Prime Disc",
    "Glaive Prime Set",
    "Helios Prime Blueprint",
    "Helios Prime Carapace",
    "Helios Prime Cerebrum",
    "Helios Prime Systems",
    "Helios Prime Set",
    "Hikou Prime Blueprint",
    "Hikou Prime Pouch",
    "Hikou Prime Stars",
    "Hikou Prime Set",
    "Hydroid Prime Blueprint",
    "Hydroid Prime Chassis",
    "Hydroid Prime Neuroptics",
    "Hydroid Prime Systems",
    "Hydroid Prime Set",
    "Kavasa Prime Collar Band",
    "Kavasa Prime Collar Blueprint",
    "Kavasa Prime Collar Buckle",
    "Kavasa Prime Collar Set",
    "Kogake Prime Blueprint",
    "Kogake Prime Boot",
    "Kogake Prime Gauntlet",
    "Kogake Prime Set",
    "Latron Prime Barrel",
    "Latron Prime Blueprint",
    "Latron Prime Receiver",
    "Latron Prime Stock",
    "Latron Prime Set",
    "Lex Prime Barrel",
    "Lex Prime Blueprint",
    "Lex Prime Receiver",
    "Lex Prime Set",
    "Loki Prime Blueprint",
    "Loki Prime Chassis",
    "Loki Prime Neuroptics",
    "Loki Prime Systems",
    "Loki Prime Set",
    "Mag Prime Blueprint",
    "Mag Prime Chassis",
    "Mag Prime Neuroptics",
    "Mag Prime Systems",
    "Mag Prime Set",
    "Mirage Prime Blueprint",
    "Mirage Prime Chassis",
    "Mirage Prime Neuroptics",
    "Mirage Prime Systems",
    "Mirage Prime Set",
    "Melee Riven Mod (Veiled)",
    "Nami Skyla Prime Blade",
    "Nami Skyla Prime Blueprint",
    "Nami Skyla Prime Handle",
    "Nami Skyla Prime Set",
    "Nekros Prime Blueprint",
    "Nekros Prime Chassis",
    "Nekros Prime Neuroptics",
    "Nekros Prime Systems",
    "Nekros Prime Set",
    "Nikana Prime Blade",
    "Nikana Prime Blueprint",
    "Nikana Prime Hilt",
    "Nikana Prime Set",
    "Nova Prime Blueprint",
    "Nova Prime Chassis",
    "Nova Prime Neuroptics",
    "Nova Prime Systems",
    "Nova Prime Set",
    "Nyx Prime Blueprint",
    "Nyx Prime Chassis",
    "Nyx Prime Neuroptics",
    "Nyx Prime Systems",
    "Nyx Prime Set",
    "Oberon Prime Blueprint",
    "Oberon Prime Chassis",
    "Oberon Prime Neuroptics",
    "Oberon Prime Systems",
    "Oberon Prime Set",
    "Odonata Prime Blueprint",
    "Odonata Prime Harness",
    "Odonata Prime Systems",
    "Odonata Prime Set",
    "Odonata Prime Wings",
    "Orthos Prime Blade",
    "Orthos Prime Blueprint",
    "Orthos Prime Handle",
    "Orthos Prime Set",
    "Paris Prime Grip",
    "Paris Prime Lower Limb",
    "Paris Prime Blueprint",
    "Paris Prime String",
    "Paris Prime Upper Limb",
    "Paris Prime Set",
    "Pistol Riven Mod (Veiled)",
    "Primed Bane of Corpus",
    "Primed Bane of Grineer",
    "Primed Bane of Infested",
    "Primed Chamber",
    "Primed Continuity",
    "Primed Cryo Rounds",
    "Primed Fast Hands",
    "Primed Flow",
    "Primed Heated Charge",
    "Primed Heavy Trauma",
    "Primed Morphic Transformer",
    "Primed Pistol Gambit",
    "Primed Pistol Mutation",
    "Primed Point Blank",
    "Primed Ravage",
    "Primed Reach",
    "Primed Regen",
    "Primed Rifle Ammo Mutation",
    "Primed Shotgun Ammo Mutation",
    "Primed Slip Magazine",
    "Primed Target Cracker",
    "Prisma Dual Cleavers",
    "Prisma Gorgon",
    "Prisma Grakata",
    "Prisma Shade",
    "Prisma Skana",
    "Prisma Tetra",
    "Prisma Veritux",
    "Rakta Ballistica",
    "Rakta Cernos",
    "Rakta Dark Dagger",
    "Reaper Prime Blade",
    "Reaper Prime Blueprint",
    "Reaper Prime Handle",
    "Reaper Prime Set",
    "Rhino Prime Blueprint",
    "Rhino Prime Chassis",
    "Rhino Prime Neuroptics",
    "Rhino Prime Systems",
    "Rhino Prime Set",
    "Rifle Riven Mod (Veiled)",
    "Sancti Castanas",
    "Sancti Magistar",
    "Sancti Tigris",
    "Saryn Prime Blueprint",
    "Saryn Prime Chassis",
    "Saryn Prime Neuroptics",
    "Saryn Prime Systems",
    "Saryn Prime Set",
    "Scindo Prime Blade",
    "Scindo Prime Blueprint",
    "Scindo Prime Handle",
    "Scindo Prime Set",
    "Secura Dual Cestra",
    "Secura Lecta",
    "Secura Penta",
    "Shotgun Riven Mod (Veiled)",
    "Sicarus Prime Barrel",
    "Sicarus Prime Blueprint",
    "Sicarus Prime Receiver",
    "Sicarus Prime Set",
    "Silva & Aegis Prime Blade",
    "Silva & Aegis Prime Blueprint",
    "Silva & Aegis Prime Guard",
    "Silva & Aegis Prime Hilt",
    "Silva & Aegis Prime Set",
    "Soma Prime Barrel",
    "Soma Prime Blueprint",
    "Soma Prime Receiver",
    "Soma Prime Stock",
    "Soma Prime Set",
    "Spira Prime Blade",
    "Spira Prime Blueprint",
    "Spira Prime Pouch",
    "Spira Prime Set",
    "Sybaris Prime Barrel",
    "Sybaris Prime Blueprint",
    "Sybaris Prime Receiver",
    "Sybaris Prime Stock",
    "Sybaris Prime Set",
    "Synoid Gammacor",
    "Synoid Heliocor",
    "Synoid Simulor",
    "Telos Akbolto",
    "Telos Boltace",
    "Telos Boltor",
    "Tigris Prime Barrel",
    "Tigris Prime Blueprint",
    "Tigris Prime Receiver",
    "Tigris Prime Stock",
    "Tigris Prime Set",
    "Trinity Prime Blueprint",
    "Trinity Prime Chassis",
    "Trinity Prime Neuroptics",
    "Trinity Prime Systems",
    "Trinity Prime Set",
    "Valkyr Prime Blueprint",
    "Valkyr Prime Chassis",
    "Valkyr Prime Neuroptics",
    "Valkyr Prime Systems",
    "Valkyr Prime Set",
    "Vasto Prime Barrel",
    "Vasto Prime Blueprint",
    "Vasto Prime Receiver",
    "Vasto Prime Set",
    "Vauban Prime Blueprint",
    "Vauban Prime Chassis",
    "Vauban Prime Neuroptics",
    "Vauban Prime Systems",
    "Vauban Prime Set",
    "Vaykor Hek",
    "Vaykor Marelok",
    "Vaykor Sydon",
    "Vectis Prime Barrel",
    "Vectis Prime Blueprint",
    "Vectis Prime Receiver",
    "Vectis Prime Stock",
    "Vectis Prime Set",
    "Venka Prime Blades",
    "Venka Prime Blueprint",
    "Venka Prime Gauntlet",
    "Venka Prime Set",
    "Volt Prime Blueprint",
    "Volt Prime Chassis",
    "Volt Prime Neuroptics",
    "Volt Prime Systems",
    "Volt Prime Set",
    "Wyrm Prime Blueprint",
    "Wyrm Prime Carapace",
    "Wyrm Prime Cerebrum",
    "Wyrm Prime Systems",
    "Wyrm Prime Set"
];
